### ISSUE TITLE
Get inventory dosen't work

### ISSUE THREAD

**Issue by wedzyou** [TheTimmaeh/node-expresstrade#1]
Hi i'm trying to get the inventory of my account but nothing concluant show up, i'm using the example project. Here what i get 
null { status: 1,
  time: 1530741677,
  current_page: 1,
  total_pages: 1,
  response:
   { items: [],
     total: '0',
     sort_parameters:
      [ [Object], [Object], [Object], [Object], [Object], [Object] ] } }
Thanks for Helping me,
Have a nice day

**Comment by TheTimmaeh** [comment]
Are you sure the API key you're using belongs to the OPSkins account that owns the items?

If so, are the items in your ExpressTrade inventory? The API only covers this inventory, not the OPSkins inventory.

**Comment by wedzyou** [comment]
Yes all the items are on my wax/expresstrade account, the apikey i'm using is on the same account . I generate this apikey on the opskins website on my account advance option

**Comment by TheTimmaeh** [comment]
Which `app_id` are you using? Which game are the items of?

Right now the default app_id is 2 which is CSGO. If you're looking for VGO items, make sure to set `{app_id: 1}` in your call:

```js
ET.IUser.GetInventory({app_id: 1}, (err, res) => {
  console.log(err, res)
})```

**Comment by tiger6201** [comment]
ET.IUser.GetInventory({app_id: 1}, (err, res) => {
  console.log(res.response)
})
