### ISSUE TITLE
PollInterval doesn't show declined offers sometimes

### ISSUE THREAD

**Issue by zaksmok** [TheTimmaeh/node-expresstrade#10]
When user declines offer very quickly it doesn't appear in pollInterval event. How can I fix it?

**Comment by TheTimmaeh** [comment]
Whats your `pollInterval`?

I'll look into it.

**Comment by zaksmok** [comment]
5 seconds

**Comment by TheTimmaeh** [comment]
Can you give some code of your setup? When exactly do you experience this issue (all the time/after starting the bot/after some run time)? Do other events trigger properly?
