### ISSUE TITLE
GetInventory shows no more than 100 items

### ISSUE THREAD

**Issue by S1ROZHA** [TheTimmaeh/node-expresstrade#2]
GetInventory shows no more than 100 items pls fix this

**Comment by TheTimmaeh** [comment]
The API limits the amount of items to 100. If you want to fetch all items in your inventory, make sure to check `total_pages` in the response and repeat the request for every page.

https://github.com/OPSkins/trade-opskins-api/blob/master/IUser/GetInventory.md
