### ISSUE TITLE
Case opening mode

### ISSUE THREAD

**Issue by KronosR97** [TheTimmaeh/node-expresstrade#4]
Hello!

Well, just asking, this code works in a case opening website? is because i've been testing and im always getting an error, i think is because the case opening key is different but i dont know, i hope somebody can help me

i was testing this 

ET.ICase.GetCaseSchema((err, res) => {
  console.log(err, res)
})

and works, but after a couple seconds i get this error

C:\Users\****\*****\node_modules\expresstrade\index.js:72
              for(var offer in res.response.offers) _pollData[res.response.offers[offer].id] = res.response.offers[offer]
                                            ^

TypeError: Cannot read property 'offers' of undefined

**Comment by TheTimmaeh** [comment]
Hey,

I'm using the module on a case opening website, thus I can confirm it works. Are you using a the API key of a VCaseUser to perform those tasks?

**Comment by KronosR97** [comment]
yeah, im using the vCaseUser key, i really dont know what is going on, this is the code im using

var ExpressTrade = require('expresstrade')

var ET = new ExpressTrade({
  apikey: '8dd15c80ee9***************',
  pollInterval: 5000
});

ET.ICase.GetCaseSchema((err, res) => {
  console.log(err, res)
});

**Comment by TheTimmaeh** [comment]
Please disable polling as it is not yet supported by the OPSkins API.

The polling uses GetOffers, which cannot get executed with a VCaseUser API key.

Simply omitting the `pollInterval` value should fix your issue.
