### ISSUE TITLE
SendOffer Missing 2FA

### ISSUE THREAD

**Issue by paparyku** [TheTimmaeh/node-expresstrade#5]
I keep getting a 2fa error when attempting to use ` ET.ITrade.SendOffer`. 

`{ status: 122,
  time: 1532467016,
  message: 'Invalid two-factor code.' }`

**Comment by TheTimmaeh** [comment]
Are you using the 2FA secret you were given by OPSkins when setting up 2FA?

**Comment by tcdeverloper1** [comment]
Hi paparyku, did you get any solution for that ? I also get 2fa error like your one even though
I have 2FA secret given by OPSkins when setting up 2FA.
