### ISSUE TITLE
I keep getting `"getOffers" of undefined` in console

### ISSUE THREAD

**Issue by AlaDyn172** [TheTimmaeh/node-expresstrade#7]
Hello,

I keep getting this error:

> TypeError: Cannot read property 'offers' of undefined
Full log:
`TypeError: Cannot read property 'offers' of undefined
1|test  |     at that.ITrade.GetOffers (/var/Socket_www2/node_modules/expresstrade/index.js:82:42)
1|test  |     at Request.e [as _callback] (/var/Socket_www2/node_modules/expresstrade/index.js:189:9)
1|test  |     at Request.self.callback (/var/Socket_www2/node_modules/request/request.js:185:22)
1|test  |     at emitTwo (events.js:106:13)
1|test  |     at Request.emit (events.js:191:7)
1|test  |     at Request.<anonymous> (/var/Socket_www2/node_modules/request/request.js:1157:10)
1|test  |     at emitOne (events.js:96:13)
1|test  |     at Request.emit (events.js:188:7)
1|test  |     at IncomingMessage.<anonymous> (/var/Socket_www2/node_modules/request/request.js:1079:12)
1|test  |     at IncomingMessage.g (events.js:292:16)
`

Someone know why?
All things works perfectly, I think this is a warning or something when are 0 offers?

**Comment by wedzyou** [comment]
getting the same issue

**Comment by damianac** [comment]
That's most likely caused by the removal of [this code](https://github.com/TheTimmaeh/node-expresstrade/commit/310750924a2c33da4a94d37430ae6e5a78e26216#diff-168726dbe96b3ce427e7fedce31bb0bcL77).
I've created pull request, hopefully it'll get noticed/pushed soon.

**Comment by TheTimmaeh** [comment]
Thanks @damianac for pointing it out, I've readded the code.

**Comment by damianac** [comment]
@TheTimmaeh You may close pull request then. Cheers
